function Hd = auto_cheby_bandstop
%AUTO_CHEBY_BANDSTOP Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
% Generated on: 08-Jan-2020 18:04:38

% Chebyshev Type I Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are in Hz.
Fs = 48000;  % Sampling Frequency

Fpass1 = 500;        % First Passband Frequency
Fstop1 = 700;       % First Stopband Frequency
Fstop2 = 4000;       % Second Stopband Frequency
Fpass2 = 4300;       % Second Passband Frequency
Apass1 = 0.5;         % First Passband Ripple (dB)
Astop  = 60;          % Stopband Attenuation (dB)
Apass2 = 1;           % Second Passband Ripple (dB)
match  = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY1 method.
h  = fdesign.bandstop(Fpass1, Fstop1, Fstop2, Fpass2, Apass1, Astop, ...
                      Apass2, Fs);
Hd = design(h, 'cheby1', 'MatchExactly', match);

% [EOF]
